apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatin-aks-sample-app
  labels:
    app: yatin-aks-sample-app
    kubernetes.azure.com/generator: devhub
  namespace: yatin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yatin-aks-sample-app
  template:
    metadata:
      labels:
        app: yatin-aks-sample-app
    spec:
      containers:
        - name: yatin-aks-sample-app
          image: yatin.azurecr.us/sample-kubernetes-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
