apiVersion: v1
kind: Service
metadata:
  name: yatin-aks-gov-sample-app
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: yatin-aks-gov-sample-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
